# .tflint.hcl
# Configuration file for TFLint, a linter for Terraform.
# This file configures rulesets and plugins to enforce best practices
# and catch potential errors in the Terraform code.

# General configuration
config {
  # This repository is focused on AWS, so we set it as the default provider.
  # This helps TFLint provide more accurate and context-aware linting.
  provider = "aws"
  
  # Format of the output. `default` is human-readable.
  # Use `json` for machine-readable output in CI/CD pipelines.
  format = "default"
  
  # Fail the TFLint process if any issues of this severity or higher are found.
  # This is crucial for enforcing quality gates in CI.
  force = false
  
  # Directories to ignore during linting.
  # The .terraform directory is generated by `terraform init` and contains
  # provider binaries and modules, which should not be linted.
  ignore_module = {
    ".terraform" = true
  }
}

# Plugin configuration for AWS-specific rules.
# This enables the AWS ruleset provided by the TFLint community.
plugin "aws" {
  enabled = true
  version = "0.27.0"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"
}

# Rule configurations can be added here to override defaults.
# For example, to enforce a specific instance type:
#
# rule "aws_instance_invalid_type" {
#   enabled = true
#   # Allowed instance types for this project
#   instance_types = [
#     "t3.micro",
#     "t3.small",
#     "m5.large",
#   ]
# }
#
# By default, we will use the recommended ruleset from the AWS plugin.