name: Release - Publish to NPM Registry

on:
  push:
    branches:
      - main

permissions:
  contents: write # to create release tags
  packages: write # to publish to npm registry (GitHub Packages)
  pull-requests: read

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    needs: build-and-test # Ensure CI passes before releasing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for semantic-release to analyze commit history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for GitHub Packages
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }} # semantic-release-npm uses NPM_TOKEN
        run: npx semantic-release