mindmap
  root((UI Component Hierarchy))
    Atomic Components
      (Button)
      (TextInput)
      (Label)
      (Icon)
      (Badge)
      (Spinner)
      (Alert)
      (ToggleSwitch)
      (Checkbox)
      (RadioButton)
    Molecular Components
      (FormGroup)
      (SearchBar)
      (OTPInput)
      (QuantityStepper)
      (ProductCard)
      (OrderCard)
      (DataTable)
      (Pagination)
      (StarRating)
      (FileUpload)
    Organism Components
      (AppHeader)
      (SidebarNav)
      (ModalDialog)
      (ChatInterface)
      (MapView)
      (DashboardWidget)
      (RegistrationForm)