mindmap
  root((Medium-Complexity UI Components))
    ::icon(fa fa-cubes)
    Forms & Inputs
      ::icon(fa fa-keyboard)
      SearchBar
      OTPInput
      QuantityStepper
      StarRating
      FileUpload
    Data Display
      ::icon(fa fa-table-list)
      ProductCard
      OrderCard
      DashboardWidget
    Navigation & Overlays
      ::icon(fa fa-sitemap)
      SidebarNav
      Pagination
      ModalDialog