require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Mapbox secret token configuration
# You should use a .netrc file for secure token management
# See: https://docs.mapbox.com/ios/maps/guides/install/
# In this example, we'll read from an environment variable for simplicity.
$MAPBOX_DOWNLOADS_TOKEN = ENV['MAPBOX_DOWNLOADS_TOKEN']

def get_hermes_version
  return '1.2.0' # Specify a fixed Hermes version
end

target 'RiderApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_path => config[:hermesPath],
    :fabric_enabled => config[:fabricEnabled],
    :hermes_enabled => config[:hermesEnabled]
  )

  # Pod for Firebase
  use_frameworks! :linkage => :static
  $FirebaseSDKVersion = '10.15.0'
  pod 'Firebase/Core', $FirebaseSDKVersion
  pod 'Firebase/Messaging', $FirebaseSDKVersion

  # Pod for Mapbox
  pod 'MapboxMaps', '10.16.1'

  target 'RiderAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    react_native_post_install(installer)
    # Flipper workaround for `use_frameworks!`
    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
  end
end